name: Data Pipeline

on:
  workflow_dispatch:
    inputs:
      run_mode:
        description: "Mode: nightly or weekly"
        required: false
        default: "nightly"
  schedule:
    - cron: '17 18 * * *'   # nightly
    - cron: '28 20 * * 1'   # Monday weekly hard recheck

permissions:
  contents: write

jobs:
  pipeline:
    runs-on: ubuntu-latest
    timeout-minutes: 240
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: { fetch-depth: 0 }

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install requests beautifulsoup4 lxml dateparser; fi

      - name: Determine mode (cron vs manual)
        id: mode
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "schedule" ]; then
            dow=$(date -u +%u)
            if [ "$dow" = "1" ]; then echo "mode=weekly" >> $GITHUB_OUTPUT; else echo "mode=nightly" >> $GITHUB_OUTPUT; fi
          else
            echo "mode=${{ inputs.run_mode }}" >> $GITHUB_OUTPUT
          fi

      - name: Scrape
        run: |
          set -e
          python scraper.py --mode "${{ steps.mode.outputs.mode }}"

      - name: QC + Learn + Generate
        run: |
          set -e
          python qc_and_learn.py --mode "${{ steps.mode.outputs.mode }}"

      - name: Validate Final Data
        run: |
          set -e
          python qc_checks.py

      - name: Commit outputs
        run: |
          set -e
          git config user.name "GitHub Actions Bot"
          git config user.email "actions-bot@users.noreply.github.com"
          if ! git diff --quiet -- data.json health.json learn.json rules.json; then
            git add data.json health.json learn.json rules.json
            git commit -m "chore: ${{ steps.mode.outputs.mode }} QC+learn update"
            git pull --rebase
            git push
          else
            echo "No changes."
          fi
