name: Nightly and Monday Recheck

on:
  workflow_dispatch: {}
  schedule:
    - cron: '15 18 * * *'   # UTC nightly
    - cron: '15 18 * * 1'   # Additional Monday run (UTC)

permissions:
  contents: write

concurrency:
  group: scrape-data
  cancel-in-progress: false

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v6
        with: { python-version: '3.11', cache: 'pip' }
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper
        run: python scraper.py
      - name: Validate JSON Schema
        run: python validate.py
      - name: Quality checks (links, dates, dups)
        run: python qc_checks.py
      - name: Generate health.json
        run: |
          python - << 'PY'
          import json, datetime, pathlib
          data = json.loads(pathlib.Path("data.json").read_text(encoding="utf-8"))
          ti = data.get("transparencyInfo", {})
          health = {
            "ok": True,
            "checkedAt": datetime.datetime.utcnow().strftime("%Y-%m-%dT%H:%M:%SZ"),
            "lastUpdated": ti.get("lastUpdated"),
            "totalListings": ti.get("totalListings"),
          }
          pathlib.Path("health.json").write_text(json.dumps(health, ensure_ascii=False, indent=2), encoding="utf-8")
          PY
      - name: Format data.json
        run: |
          python - << 'PY'
          import json, pathlib
          p = pathlib.Path("data.json")
          data = json.loads(p.read_text(encoding="utf-8"))
          p.write_text(json.dumps(data, ensure_ascii=False, indent=2), encoding="utf-8")
          PY
      - name: Commit updated data.json and health.json if changed
        run: |
          git config user.name "actions-user"
          git config user.email "actions@users.noreply.github.com"
          CHANGED="$(git status --porcelain data.json health.json)"
          if [[ -n "$CHANGED" ]]; then
            git add data.json health.json
            git commit -m "chore(data): automated refresh with validation"
            git push
          else
            echo "No changes to commit."
          fi

  lighthouse:
    runs-on: ubuntu-latest
    needs: scrape
    if: ${{ vars.PAGES_URL != '' }} # Set PAGES_URL repo variable to enable
    steps:
      - uses: actions/checkout@v4
      - name: Audit URLs using Lighthouse CI
        uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            ${{ vars.PAGES_URL }}/
            ${{ vars.PAGES_URL }}/health.json
          budgetPath: ./.github/lighthouse/budget.json
          uploadArtifacts: true
