name: Nightly and Monday Recheck

on:
  schedule:
    - cron: "30 19 * * *"   # 1:00 AM IST daily (UTC)
    - cron: "30 20 * * 0"   # 2:00 AM IST Monday (UTC)
  workflow_dispatch:        # allow manual Run workflow from Actions tab

permissions:
  contents: write           # needed so the job can commit data.json

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # BEGIN: Replace your old middle steps with these Python steps
      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run scraper
        run: python scraper.py
      # END: Python steps

      - name: Commit updated data.json
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add data.json
          git commit -m "Auto: refresh data.json" || echo "No changes"
          git push
